---
# tasks file for create-dir
- name: Creating folder on remote server
  file:
          path: "{{ item.dir_path }}"
          state: directory
          owner: "{{ item.dir_owner }}"
          group: "{{ item.dir_group }}" 
          mode: "{{ item.dir_mode }}"
  loop: "{{ dir_inf }}"
  when: dir_inf is defined

- name: Creating folder on remote server
  file:
          path: "{{ item.dir_path }}"
          state: directory
          owner: "{{ dir_owner }}"
          group: "{{ dir_group }}" 
          mode: "{{ dir_mode }}"
  loop: "{{ common_dir_info }}"
  when: common_dir_info is defined